### ISSUE TITLE
should the prefix be configurable?

### ISSUE THREAD

**Issue by nsheff** [databio/folderfun#3]
Right now `folderfun` uses the prefix `ff` for folder functions.

Earlier, before I made this into a package, I used the prefix `dir`. 

Should this be customizable? Or should we force you to use `ff` so that things are a bit more cross-compatible?

**Comment by stolarczyk** [comment]
I think we should stick to `ff`. It is intuitive as it corresponds to the package function names (`setff`, `listff`)

**Comment by vreuter** [comment]
I think `dir` makes sense if the function created were named according to what the stored value represents, e.g. `dirRes`, but that since it's named by the literal variable stored, the `ff` prefix makes more clearly conveys to code reader less familiar with this package that something package-specific is going on.

**Comment by nsheff** [comment]
I guess we'll keep it non-configurable for now.
